### ISSUE TITLE
Subscribed list doesn’t show all subscribed communities

### ISSUE THREAD

**Issue by jspayd** [mormaer/Mlem#281] opened 2023-06-25 07:16 UTC
**Describe the bug**
What did you do to trigger the bug?
View the list of communities I’m subscribed to

**Expected Behavior**
What did you expect to happen?
I see all the communities I’m subscribed to

**Actual Behavior**
What actually happened?
Only a few of my subscribed communities are in the list

**To Reproduce**
What steps do I need to take to trigger the bug?
View the list of communities you’re subscribed to

**Mlem Information:**
0.1.0 (14)

**Additional Context**
I couldn’t find a pattern to which communities appear in the list. Most of the ones in the list are from lemmy.world where my account lives, but I think that’s just because most of the communities I’m subscribed to are on lemmy.world. Some communities from other instances are in the list.

Visiting a community in Mlem does not make it appear in my subscribed list.

This doesn’t appear to be an issue with instances defederating, because mlemapp@lemmy.ml does not appear in the list, but afaik lemmy.ml and lemmy.world are still federated with each other.

**Comment by z01L** [comment] 2023-06-25 09:13
I’m also experiencing the same problem. Only 10 out of 49 of my subscribed communities are appearing.

**Comment by ShadowJonathan** [comment] 2023-06-25 15:31
Duplicate of #242

**Closed by ShadowJonathan** 2023-06-25 15:31 UTC
Labels: bug
