### ISSUE TITLE
Only the first NSFW image is censored

### ISSUE THREAD

**Issue by ShadowJonathan** [mormaer/Mlem#291] opened 2023-06-25 13:49 UTC
As in the title, also noted in #61

**Comment by ShadowJonathan** [comment] 2023-06-25 13:50
@EricBAndrews I can't yet affect the Development Tracker, but previously this was in Under Development

**Comment by JakeShirley** [comment] 2023-06-25 15:20
I just tried to reproduce this in a community feed but cannot.  All of the posts I am seeing are blurred.

Any tips?

**Comment by ShadowJonathan** [comment] 2023-06-25 15:28
TFF shows an "All" feed, not sure what else to try than that.

cc @BaelfireNightshd and @EricBAndrews since they might know more.

**Comment by BaelfireNightshd** [comment] 2023-06-25 16:38
I think my original test post was removed by moderation for some reason... I finally got another account and was going to try to get a screenshot, but since it might have been removed (I sorted by new and found a post in the mlemapp community that I made shortly before the test post and couldn't find the test post I made. I'll check on web when I get a chance to see if it's just the mlem client not showing it) it's hard to demonstrate short of finding an actual NSFW example (which I'm sure you can understand me being uncomfortable with sharing that on GitHub).

**Comment by BaelfireNightshd** [comment] 2023-06-25 17:08
I reached out to a mod to ask about the removal.

**Comment by JakeShirley** [comment] 2023-06-25 20:42
You could spin up a community and make an example post that is marked NSFW if you feel more comfortable that way.  All of the NSFW communities and posts I've seen seem to be working as far as I can tell.

**Comment by BaelfireNightshd** [comment] 2023-06-25 21:17
It's back up! https://beehaw.org/post/710425

Interestingly, none of the images are blurred. Maybe because I put text before? Maybe because the images are all in the body?

**Comment by EricBAndrews** [comment] 2023-06-26 02:11
Child issue of #308

**Comment by BrooklynMan** [comment] 2023-06-26 19:56
exactly. contents of the Description text box, including any images linked there, are NOT censored by the Lemmy API. We, however, should apply NSFW blur to all images there, too.

**Comment by EricBAndrews** [comment] 2023-06-29 16:34
Closed in #336

**Closed by EricBAndrews** 2023-06-29 16:34 UTC
Labels: bug, TestFlight Feedback
