### ISSUE TITLE
Share as image

### ISSUE THREAD

**Issue by Emiliaaah** [mormaer/Mlem#263] opened 2023-06-24 11:31 UTC
## Introduction
I think it would be cool if we could share a post in the form of an image. Here are some examples:

Apollo
![image](https://github.com/mormaer/Mlem/assets/55017867/40d4d1d6-3b98-4bc3-808d-6f7c5b0529ec)

Toot!
![image](https://github.com/mormaer/Mlem/assets/55017867/b8a35670-838e-4ae2-b72f-b9a0b72ffa8d)

## Requirements
An option to share as image instead of only being able to share a link.

**Comment by ShadowJonathan** [comment] 2023-06-25 15:38
Duplicate of https://github.com/mormaer/Mlem/issues/161

Also I didn't know Toot had an export feature 👀

**Closed by ShadowJonathan** 2023-06-25 15:38 UTC
Labels: enhancement
