### ISSUE TITLE
* Not all Subscribed Communities show the in the subscribed community list

### ISSUE THREAD

**Issue by adude007** [mormaer/Mlem#294] opened 2023-06-25 14:09 UTC
**Describe the bug**
Subscribed to communities in app

**Expected Behavior**
Community to be listed in the app

**Actual Behavior**
Only listed in subscription list on a mobile/desktop browser

**To Reproduce**
Not sure was working ok for a while. 

**Mlem Information:**
0.1.0 (14)

**Comment by ShadowJonathan** [comment] 2023-06-25 14:10
Duplicate of #242

**Closed by ShadowJonathan** 2023-06-25 14:10 UTC
Labels: bug
